FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=gmnotmg
ENV N8N_BASIC_AUTH_PASSWORD=Jinseyeon99!

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=http
ENV WEBHOOK_TUNNEL_URL=https://your-subdomain.fly.dev

EXPOSE 5678
